# tomcat
server:
  port: 8081
  servlet:
    context-path: /

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  # 实体扫描
  type-aliases-package: com.e4.entity
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: 0
      logic-not-delete-value: 1
    banner: false
  # 执行器
  executor-type: batch
  configuration:
    # 一级缓存开启（微服务需关闭）
    local-cache-scope: session
    # 关闭二级缓存
    cache-enabled: false
    # 空字段自动赋值
    call-setters-on-nulls: true
    jdbc-type-for-null: null


spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
  # 事务
  transaction:
    rollback-on-commit-failure: true

path:
  md: /home/coldairance/blog/files/
